### ISSUE TITLE
Anlegen von /etc/mrtg/dhcpbat$bat.sh fehlerhaft

### ISSUE THREAD

**Issue by ChristianDresel** [ChristianDresel/gatewaykxv2#2]
Da steht noch ein haufen quatsch drinnen, muss man sich nochmal angucken die Befehle werden wohl ausgeführt und nur die Zahl reingeschrieben oder so...

**Comment by adrianschmutzler** [comment]
Siehe
https://github.com/ChristianDresel/gatewaykxv2/pull/12/commits/02383e7f15badd8cab1ceeb0625ff64d9d76ad1d
