### ISSUE TITLE
fe80 Adresse falsch

### ISSUE THREAD

**Issue by ChristianDresel** [ChristianDresel/gatewaykxv2#7]
#fe80 IPv6 holen:
fe80=$(ip -6 addr show $ethernetinterface | grep "inet6 fe80" | grep -v "inet6 fe80::1" | tail -n 1 | cut -d " " -f6)
echo "Wir nutzen folgende fe80 IPv6: $fe80"

holt die fe80 mit /64, radvd hätte sie gerne ohne /64 sonst startet er nicht mehr...

**Comment by adrianschmutzler** [comment]
Siehe:
https://github.com/ChristianDresel/gatewaykxv2/pull/12/commits/c63a5d0efeec20d50ef6c5a398bc485500367377
